#pragma once

namespace sre
{

#define SCANCODE_MASK (1<<30)
#define SCANCODE_TO_KEYCODE(X)  (X | SCANCODE_MASK)

enum ScanCode
{
	SCANCODE_F1 = 58,
	SCANCODE_F2 = 59,
	SCANCODE_F3 = 60,
	SCANCODE_F4 = 61,
	SCANCODE_F5 = 62,
	SCANCODE_F6 = 63,
	SCANCODE_F7 = 64,
	SCANCODE_F8 = 65,
	SCANCODE_F9 = 66,
	SCANCODE_F10 = 67,
	SCANCODE_F11 = 68,
	SCANCODE_F12 = 69,

	SCANCODE_PRINTSCREEN = 70,
	SCANCODE_SCROLLLOCK = 71,
	SCANCODE_PAUSE = 72,
	SCANCODE_INSERT = 73,

	SCANCODE_HOME = 74,
	SCANCODE_PAGEUP = 75,
	SCANCODE_DELETE = 76,
	SCANCODE_END = 77,
	SCANCODE_PAGEDOWN = 78,
	SCANCODE_RIGHT = 79,
	SCANCODE_LEFT = 80,
	SCANCODE_DOWN = 81,
	SCANCODE_UP = 82,

	SCANCODE_KP_DIVIDE = 84,
	SCANCODE_KP_MULTIPLY = 85,
	SCANCODE_KP_MINUS = 86,
	SCANCODE_KP_PLUS = 87,
	SCANCODE_KP_ENTER = 88,
	SCANCODE_KP_1 = 89,
	SCANCODE_KP_2 = 90,
	SCANCODE_KP_3 = 91,
	SCANCODE_KP_4 = 92,
	SCANCODE_KP_5 = 93,
	SCANCODE_KP_6 = 94,
	SCANCODE_KP_7 = 95,
	SCANCODE_KP_8 = 96,
	SCANCODE_KP_9 = 97,
	SCANCODE_KP_0 = 98,
	SCANCODE_KP_PERIOD = 99,

	SCANCODE_LCTRL	= 224,
	SCANCODE_LSHIFT = 225,
	SCANCODE_LALT	= 226,
	SCANCODE_LGUI	= 227,
	SCANCODE_RCTRL	= 228,
	SCANCODE_RSHIFT = 229,
	SCANCODE_RALT	= 230
};

enum Key
{
	KEY_a = 'a',
	KEY_b = 'b',
	KEY_c = 'c',
	KEY_d = 'd',
	KEY_e = 'e',
	KEY_f = 'f',
	KEY_g = 'g',
	KEY_h = 'h',
	KEY_i = 'i',
	KEY_j = 'j',
	KEY_k = 'k',
	KEY_l = 'l',
	KEY_m = 'm',
	KEY_n = 'n',
	KEY_o = 'o',
	KEY_p = 'p',
	KEY_q = 'q',
	KEY_r = 'r',
	KEY_s = 's',
	KEY_t = 't',
	KEY_u = 'u',
	KEY_v = 'v',
	KEY_w = 'w',
	KEY_x = 'x',
	KEY_y = 'y',
	KEY_z = 'z',

	KEY_0 = '0',
	KEY_1 = '1',
	KEY_2 = '2',
	KEY_3 = '3',
	KEY_4 = '4',
	KEY_5 = '5',
	KEY_6 = '6',
	KEY_7 = '7',
	KEY_8 = '8',
	KEY_9 = '9',
	
	KEY_RETURN		= '\r',
	KEY_ESC			= '\033',
	KEY_SPACE		= ' ',
	KEY_BACKSPACE	= '\b',
	KEY_TAB			= '\t',

	KEY_F1 = SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_F1),
	KEY_F2 = SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_F2),
	KEY_F3 = SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_F3),
	KEY_F4 = SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_F4),
	KEY_F5 = SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_F5),
	KEY_F6 = SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_F6),
	KEY_F7 = SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_F7),
	KEY_F8 = SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_F8),
	KEY_F9 = SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_F9),
	KEY_F10 = SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_F10),
	KEY_F11 = SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_F11),
	KEY_F12 = SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_F12),

	KEY_UP			= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_UP),
	KEY_DOWN		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_DOWN),
	KEY_LEFT		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_LEFT),
	KEY_RIGHT		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_RIGHT),
	KEY_INSERT		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_INSERT),
	KEY_HOME		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_HOME),
	KEY_END			= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_END),
	KEY_PAGEUP		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_PAGEUP),
	KEY_PAGEDOWN	= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_PAGEDOWN),
	KEY_DELETE		= '\177',

	KEYPAD_DIVIDE	= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_DIVIDE),
	KEYPAD_MULTIPLY	= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_MULTIPLY),
	KEYPAD_MINUS	= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_MINUS),
	KEYPAD_PLUS		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_PLUS),
	KEYPAD_ENTER	= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_ENTER),
	KEYPAD_1		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_1),
	KEYPAD_2		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_2),
	KEYPAD_3		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_3),
	KEYPAD_4		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_4),
	KEYPAD_5		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_5),
	KEYPAD_6		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_6),
	KEYPAD_7		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_7),
	KEYPAD_8		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_8),
	KEYPAD_9		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_9),
	KEYPAD_0		= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_0),
	KEYPAD_PERIOD	= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_KP_PERIOD),

	KEY_LCTRL	= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_LCTRL),
	KEY_LSHIFT	= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_LSHIFT),
	KEY_LALT	= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_LALT),
	KEY_RCTRL	= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_RCTRL),
	KEY_RSHIFT	= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_RSHIFT),
	KEY_RALT	= SCANCODE_TO_KEYCODE(ScanCode::SCANCODE_RALT)
};

enum MouseButton
{
	MOUSEBUTTON_LEFT = 1,
	MOUSEBUTTON_MIDDLE = 2,
	MOUSEBUTTON_RIGHT = 3,
	MOUSEBUTTON_4 = 4,
	MOUSEBUTTON_5 = 5,
	MOUSEBUTTON_6 = 6,
	MOUSEBUTTON_7 = 7,
	MOUSEBUTTON_8 = 8
};

} // namespace
